Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 16:07:46) [MSC v.1900 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> X=5
>>> y=13.5
>>> c=X+y
>>> type(c)
<class 'float'>
>>> nombre="Noel
SyntaxError: EOL while scanning string literal
>>> nombre="Noel"
>>> apellido="Castro"
>>> nombreCompleto= nombre+apellido
>>> nombreCompleto
'NoelCastro'
>>> nombreCompleto= nombre+" "+apellido
>>> nombreCompleto
'Noel Castro'
>>> 7 + 2
9
>>> 4+ 1-
SyntaxError: invalid syntax
>>> uff
Traceback (most recent call last):
  File "<pyshell#13>", line 1, in <module>
    uff
NameError: name 'uff' is not defined
>>> 1-2+3
2
>>> 2+4*3
14
>>> (2+4)*3
18
>>> 
